const wordsByCategory = {
    Animals: [
        { word: 'elephant', clue: 'A large mammal with a trunk' },
        { word: 'giraffe', clue: 'The tallest living terrestrial animal' },
        { word: 'kangaroo', clue: 'A hopping animal from Australia' },
        { word: 'penguin', clue: 'A flightless bird that swims' },
        { word: 'octopus', clue: 'A sea creature with eight arms' },
        { word: 'cheetah', clue: 'The fastest land animal' },
        { word: 'squirrel', clue: 'A small animal known for climbing trees' },
        { word: 'hippopotamus', clue: 'A large mammal often found in rivers in Africa' },
        { word: 'flamingo', clue: 'A bird known for standing on one leg' },
        { word: 'dolphin', clue: 'A smart marine mammal known for its playful nature' },
        { word: 'gorilla', clue: 'A large ape known for its strength' },
        { word: 'platypus', clue: 'An egg-laying mammal from Australia' },
        { word: 'armadillo', clue: 'An animal known for its armored shell' },
        { word: 'rhinoceros', clue: 'A large animal known for its horn on its snout' },
        { word: 'lobster', clue: 'A type of large marine crustacean' },
        { word: 'koala', clue: 'An Australian mammal that eats eucalyptus leaves' },
        { word: 'jellyfish', clue: 'A gelatinous sea creature with tentacles' },
        { word: 'seahorse', clue: 'A small marine fish with a horse-like head' },
        { word: 'chameleon', clue: 'A lizard known for changing its color' },
        { word: 'tarantula', clue: 'A large and hairy spider' },
        { word: 'meerkat', clue: 'A small animal known for standing upright' },
        { word: 'panda', clue: 'A bear known for its black and white fur' },
        { word: 'walrus', clue: 'A large marine mammal with long tusks' },
        { word: 'parrot', clue: 'A bird known for its ability to mimic sounds' },
        { word: 'buffalo', clue: 'A large animal known for its hump and horns' },
        { word: 'mongoose', clue: 'A small carnivorous mammal' },
        { word: 'falcon', clue: 'A bird of prey known for its speed' },
        { word: 'lemur', clue: 'A primate known for its large eyes' },
        { word: 'iguana', clue: 'A large lizard known for its crest' },
        { word: 'toucan', clue: 'A tropical bird known for its large bill' }
    ],
    Countries: [
 { word: 'brazil', clue: 'Country famous for its carnival and samba' },
{ word: 'japan', clue: 'Land of the Rising Sun' },
{ word: 'egypt', clue: 'Country known for pyramids' },
{ word: 'canada', clue: 'Second largest country by area' },
{ word: 'india', clue: 'Country with the second-highest population' },
{ word: 'france', clue: 'European country known for the Eiffel Tower' },
{ word: 'mexico', clue: 'Country famous for tacos and sombreros' },
{ word: 'china', clue: 'Country with the largest population' },
{ word: 'australia', clue: 'Country known for kangaroos and the Great Barrier Reef' },
{ word: 'italy', clue: 'Country famous for pizza and the Colosseum' },
{ word: 'russia', clue: 'Largest country in the world by area' },
{ word: 'kenya', clue: 'African country known for its savannas and wildlife' },
{ word: 'greece', clue: 'Country known for ancient mythology and the Olympics' },
{ word: 'peru', clue: 'Country home to Machu Picchu' },
{ word: 'spain', clue: 'European country known for flamenco dancing' },
{ word: 'thailand', clue: 'Country in Southeast Asia known for its beaches and temples' },
{ word: 'ireland', clue: 'Island nation known for its green hills and leprechauns' },
{ word: 'iceland', clue: 'Nordic country known for geysers and volcanoes' },
{ word: 'germany', clue: 'European country known for its engineering and Oktoberfest' },
{ word: 'nepal', clue: 'Country home to Mount Everest' },
{ word: 'morocco', clue: 'North African country known for its desert and spices' },
{ word: 'belgium', clue: 'European country famous for chocolate and waffles' },
{ word: 'sweden', clue: 'Scandinavian country known for its fjords and Vikings' },
{ word: 'turkey', clue: 'Country that bridges Asia and Europe' },
{ word: 'argentina', clue: 'South American country known for tango dancing' },
{ word: 'norway', clue: 'Country known for fjords and northern lights' },
{ word: 'vietnam', clue: 'Southeast Asian country known for its history and cuisine' },
{ word: 'jamaica', clue: 'Caribbean island nation known for reggae music' },
{ word: 'portugal', clue: 'European country famous for its maritime history' },
{ word: 'finland', clue: 'Nordic country known for its lakes and saunas' },
    ],
    Science: [
        { word: 'ecosystem', clue: 'A community of interacting organisms and their environment' },
        { word: 'genetics', clue: 'The study of heredity and the variation of inherited characteristics' },
        { word: 'asteroid', clue: 'A small rocky body orbiting the sun' },
        { word: 'climate', clue: 'The long-term weather patterns of a region' },
        { word: 'neptune', clue: 'A distant, blue planet in our solar system' },
        { word: 'microscope', clue: 'An instrument used to see objects that are too small for the naked eye' },
        { word: 'voltage', clue: 'An electric potential difference between two points' },
        { word: 'algorithm', clue: 'A process or set of rules to be followed in calculations' },
        { word: 'bacteria', clue: 'Microscopic living organisms, often one-celled' },
        { word: 'chromosome', clue: 'A thread-like structure of nucleic acids and protein found in the nucleus of most living cells' },
        { word: 'delta', clue: 'A landform at the mouth of a river created by sediment deposits' },
        { word: 'enzyme', clue: 'Proteins that act as biological catalysts' },
        { word: 'fossil', clue: 'The remains or impression of a prehistoric organism preserved in petrified form' },
        { word: 'glacier', clue: 'A slowly moving mass of ice' },
        { word: 'habitat', clue: 'The natural home or environment of an animal, plant, or other organism' },
        { word: 'isotope', clue: 'Each of two or more forms of the same element, containing equal numbers of protons but different numbers of neutrons' },
        { word: 'joule', clue: 'A unit of energy in the metric system' },
        { word: 'keystone', clue: 'A species on which other species in an ecosystem largely depend' },
    ],
    SocialStudies:[
        { word: 'democracy', clue: 'A system of government by the whole population' },
        { word: 'constitution', clue: 'A body of fundamental principles according to which a state is governed' },
        { word: 'revolution', clue: 'A forcible overthrow of a government in favor of a new system' },
        { word: 'renaissance', clue: 'A period of cultural and artistic change in Europe from the 14th to the 17th century' },
        { word: 'globalization', clue: 'The process by which businesses develop international influence' },
        { word: 'pyramids', clue: 'Ancient monumental structures built in Egypt' },
        { word: 'suffrage', clue: 'The right to vote in political elections' },
        { word: 'feudalism', clue: 'A medieval European social system in which land was owned by lords' },
        { word: 'renaissance', clue: 'A period in European history marking the transition from the Middle Ages to Modernity' },
        { word: 'inflation', clue: 'A general increase in prices and fall in the purchasing value of money' },
        { word: 'capitalism', clue: 'An economic system in which a country trade is controlled by private owners' },
        { word: 'philosophy', clue: 'The study of the fundamental nature of knowledge, reality, and existence' },
        { word: 'archaeology', clue: 'The study of human history through the excavation of sites and the analysis of artifacts' },
        { word: 'confederation', clue: 'An organization that consists of a number of parties united in an alliance' },
        { word: 'dictatorship', clue: 'A form of government where a country is ruled by one person' },
        { word: 'enlightenment', clue: 'An intellectual movement in Europe in the 17th and 18th centuries emphasizing reason and individualism' },
        { word: 'federalism', clue: 'A system of government in which entities such as states share power with a national government' },
        { word: 'geography', clue: 'The study of the physical features of the earth' },
        { word: 'hieroglyphics', clue: 'A system of writing used in ancient Egypt' },
    ],
  };
  
  export function getRandomWord(category) {
    const words = wordsByCategory[category] || [];
    return words[Math.floor(Math.random() * words.length)];
  }
  